module.exports = {
  $schema: "./schema.json",
  $version: "1.0.0",
  spacing: {
    baseline: "4",
    multiplier: {
      1: "1",
      2: "2",
      3: "4",
      4: "8",
      5: "14",
      6: "22",
    },
    pageWidth: "65em",
    p2p: "",
    p2h: "",
    h2p: "",
    h2h: "",
  },
  theme: {
    light: {
      primary: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      accent: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      error: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      warning: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      info: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      success: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
    },
    dark: {
      primary: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      accent: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      error: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      warning: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      info: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
      success: {backgroundColor: "", color: "", disabled: "", invertedDisabled: ""},
    },
  },
  font: {
    scale: "1.13",
    body: {
      family: "sans-serif",
      size: "20px",
      lineHeight: "",
      weight: "bold",
      style: "italic",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    heading: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h1_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h2_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h3_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h4_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h5_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h6_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    subheading: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    pullQuote: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
  },
  zIndex: {
    1: "1000",
    2: "2000",
    3: "3000",
    4: "4000",
    5: "5000",
    6: "6000",
  },
  shadow: {
    1: "1px 1px",
    2: "1px 1px",
    3: "1px 1px",
    4: "1px 1px",
    5: "1px 1px",
    6: "1px 1px",
  },
  border: "1px solid currentColor",
  borderRadius: "1",
  breakpoint: {
    1: "400px",
    2: "600px",
    3: "800px",
    4: "1000px",
    5: "1200px",
    6: "1600px",
  },
  timing: {
    xslow: "",
    slow: "",
    medium: "",
    fast: "",
    xfast: "",
    defaults: {
      speed: "",
      in: "",
      out: "",
      inout: "",
    },
  },
};
