module.exports = {
  $schema: "./schema.json",
  $version: "1.0.0",
  spacing: {
    baseline: 4,
    multiplier_1: 1,
    multiplier_2: 2,
    multiplier_3: 4,
    multiplier_4: 8,
    multiplier_5: 14,
    multiplier_6: 22,
    pageWidth: "65em",
    p2p: "",
    p2h: "",
    h2p: "",
    h2h: "",
  },
  theme: {
    light: {
      primary: {background: "", text: "", disabled: "", inverseDisabled: ""},
      accent: {background: "", text: "", disabled: "", inverseDisabled: ""},
      error: {background: "", text: "", disabled: "", inverseDisabled: ""},
      warn: {background: "", text: "", disabled: "", inverseDisabled: ""},
      info: {background: "", text: "", disabled: "", inverseDisabled: ""},
      success: {background: "", text: "", disabled: "", inverseDisabled: ""},
    },
    dark: {
      primary: {background: "", text: "", disabled: "", inverseDisabled: ""},
      accent: {background: "", text: "", disabled: "", inverseDisabled: ""},
      error: {background: "", text: "", disabled: "", inverseDisabled: ""},
      warn: {background: "", text: "", disabled: "", inverseDisabled: ""},
      info: {background: "", text: "", disabled: "", inverseDisabled: ""},
      success: {background: "", text: "", disabled: "", inverseDisabled: ""},
    },
  },
  font: {
    scale: "",
    body: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    heading: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h1_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h2_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h3_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h4_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h5_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    h6_override: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    subheading: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
    pullQuote: {
      family: "",
      size: "",
      lineHeight: "",
      weight: "",
      style: "",
      decoration: "",
      transform: "",
      letterSpacing: "",
      shadow: "",
    },
  },
  depth: {
    0: "",
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
  },
  border: {radius: "", style: ""},
  breakpoint: {
    1: "400px",
    2: "600px",
    3: "800px",
    4: "1000px",
    5: "1200px",
    6: "1600px",
  },
  timing: {
    xslow: "",
    slow: "",
    medium: "",
    fast: "",
    xfast: "",
    defaults: {
      speed: "",
      in: "",
      out: "",
      inout: "",
    },
  },
};
