
// AUTOGENERATED FILE, DO NOT EDIT
import { css } from 'lit';

export const utilityStyles = css`
:root {
  --fui-animation-speed-slow: 0.5s;
  --fui-animation-speed-medium: 0.3s;
  --fui-animation-speed-fast: 0.1s;

  --fui-animation-default-speed: var(--fui-animation-speed-medium);
  --fui-animation-default-timing-function: ease-in-out;



  --fui-border-width: 1px;
  --fui-border-radius: 0.25rem;
  --fui-border-radius-pill: 9999px;


  /* These do not change between light/dark */
  --fui-color-primary: #697164;
  --fui-color-accent: #c3B799;
  --fui-color-complement: #6D6F7F;

  --fui-color-grey-0: #ffffff;
  --fui-color-grey-50: #fafafa;
  --fui-color-grey-100: #f5f5f5;
  --fui-color-grey-400: #bdbdbd;
  --fui-color-grey-500: #9e9e9e;
  --fui-color-grey-900: #212121;
  --fui-color-grey-950: #121212;
  --fui-color-grey-1000: #1e1c1c;

  --fui-color-success-100: #c8e6c9;
  --fui-color-success-400: #66bb6a;
  --fui-color-success-500: #4caf50;
  --fui-color-success-900: #1b5e20;

  --fui-color-info-100: #bbdefb;
  --fui-color-info-400: #42a5f5;
  --fui-color-info-500: #2196f3;
  --fui-color-info-900: #0d47a1;

  --fui-color-warn-100: #ffe0b2;
  --fui-color-warn-400: #ffb74d;
  --fui-color-warn-500: #ff9800;
  --fui-color-warn-900: #e65100;

  --fui-color-danger-100: #ffcdd2;
  --fui-color-danger-400: #ef5350;
  --fui-color-danger-500: #f44336;
  --fui-color-danger-900: #b71c1c;

  --fui-color-dark-text: var(--fui-color-grey-950);
  --fui-color-dark-text-disabled: var(--fui-color-grey-500);
  --fui-color-dark-text-visited: var(--fui-color-grey-900);

  --fui-color-light-text: var(--fui-color-grey-50);
  --fui-color-light-text-disabled: var(--fui-color-grey-400);
  --fui-color-light-text-visited: var(--fui-color-grey-100);



  --fui-page-width: 65rem;

  --fui-spacing-base: 4px;
  --fui-spacing-y-min: calc(var(--fui-spacing-base) * 10);
  --fui-spacing-x-min: calc(var(--fui-spacing-base) * 10);
  --fui-spacing-y-max: calc(var(--fui-spacing-base) * 20);
  --fui-spacing-x-max: calc(var(--fui-spacing-base) * 24);
  --fui-spacing-static: var(--fui-spacing-y-min) var(--fui-spacing-x-min);
  --fui-spacing-responsive-y: clamp(var(--fui-spacing-y-min), calc(100vw * 0.08), var(--fui-spacing-y-max));
  --fui-spacing-responsive-x: clamp(var(--fui-spacing-x-min), 5%, var(--fui-spacing-x-max));
  --fui-spacing-responsive: var(--fui-spacing-responsive-y) var(--fui-spacing-responsive-x);
  --fui-spacing-page-y: var(--fui-spacing-responsive-y);
  --fui-spacing-page-x: max(var(--fui-spacing-x-min), calc((100vw - var(--fui-page-width)) / 2));
  --fui-spacing-page: var(--fui-spacing-page-y) var(--fui-spacing-page-x);
  --fui-spacing-text: clamp(var(--fui-spacing-y-min), calc(100vw * 0.04), 2rem);



  
  --fui-body-font-family: 'Open Sans', sans-serif;
  --fui-body-font-size: max(1rem, 18px);
  --fui-body-line-height: 1.8;
  --fui-body-font-weight: 400;
  --fui-body-font-style: normal;
  --fui-body-font-variant: normal;
  --fui-body-font-kerning: normal;

  --fui-heading-line-height: 1.5;
  --fui-heading-font-family: 'Josefin Sans', sans-serif;
  --fui-font-size-scale-min: 1.1;
  --fui-font-size-scale-max: 1.33;
  --fui-font-size-scale: 1.1;
  --fui-h6-font-size: var(--fui-body-font-size);
  --fui-h5-font-size: calc(var(--fui-h6-font-size) * var(--fui-font-size-scale));
  --fui-h4-font-size: calc(var(--fui-h5-font-size) * var(--fui-font-size-scale));
  --fui-h3-font-size: calc(var(--fui-h4-font-size) * var(--fui-font-size-scale));
  --fui-h2-font-size: calc(var(--fui-h3-font-size) * var(--fui-font-size-scale));
  --fui-h1-font-size: calc(var(--fui-h2-font-size) * var(--fui-font-size-scale));



  --fui-z-index-drawer: 1000;
  --fui-z-index-dialog: 2000;
  --fui-z-index-dropdown: 3000;
  --fui-z-index-alert-group: 4000;
  --fui-z-index-tooltip: 5000;
}

:root, .light {
  color-scheme: light;
  --fui-theme-neutral-color: var(--fui-color-dark-text);
  --fui-theme-neutral-color-disabled: var(--fui-color-dark-text);
  --fui-theme-neutral-color-visited: var(--fui-color-dark-text);
  --fui-theme-neutral-background-color: var(--fui-color-neutral-50);

  --fui-theme-primary-color: var(--fui-color-light-text);
  --fui-theme-primary-color-disabled: var(--fui-color-light-text-disabled);
  --fui-theme-primary-color-visited: var(--fui-color-light-text-visited);
  --fui-theme-primary-background-color: var(--fui-color-primary);
  
  --fui-theme-accent-color: var(--fui-color-light-text);
  --fui-theme-accent-color-disabled: var(--fui-color-light-text-disabled);
  --fui-theme-accent-color-visited: var(--fui-color-light-text-visited);
  --fui-theme-accent-background-color: var(--fui-color-accent);

  --fui-theme-complement-color: var(--fui-color-light-text);
  --fui-theme-complement-color-disabled: var(--fui-color-light-text-disabled);
  --fui-theme-complement-color-visited: var(--fui-color-light-text-visited);
  --fui-theme-complement-background-color: var(--fui-color-complement);
}

.primary {
  color: var(--fui-theme-primary-color);
  background-color: var(--fui-theme-primary-background-color);
}

.primary :visited {
  color: var(--fui-theme-primary-color-visited);
}

.primary--hover:hover,
.primary--focus:focus,
.primary--focus:hover,
.primary--focus-within:focus-within,
.primary--active:active,
.primary--disabled:disabled {
  color: var(--fui-theme-primary-color);
  background-color: var(--fui-theme-primary-background-color)}

.primary-inverse {
  color: var(--fui-theme-primary-background-color);
  background-color: var(--fui-theme-primary-color);
}

.primary-inverse :visited {
  color: var(--fui-theme-primary-color-visited);
}

.primary-inverse--hover:hover,
.primary-inverse--focus:focus,
.primary-inverse--focus:hover,
.primary-inverse--focus-within:focus-within,
.primary-inverse--active:active,
.primary-inverse--disabled:disabled {
  color: var(--fui-theme-primary-background-color);
  background-color: var(--fui-theme-primary-color)}

.c-primary-color {
  color: var(--fui-theme-primary-color);
}

.c-primary-color--hover:hover,
.c-primary-color--focus:focus,
.c-primary-color--focus:hover,
.c-primary-color--focus-within:focus-within,
.c-primary-color--active:active,
.c-primary-color--disabled:disabled {
  color: var(--fui-theme-primary-color)}

.c-primary-background-color {
  color: var(--fui-theme-primary-background-color);
}

.c-primary-background-color--hover:hover,
.c-primary-background-color--focus:focus,
.c-primary-background-color--focus:hover,
.c-primary-background-color--focus-within:focus-within,
.c-primary-background-color--active:active,
.c-primary-background-color--disabled:disabled {
  color: var(--fui-theme-primary-background-color)}

.bg-primary-color {
  background-color: var(--fui-theme-primary-color);
}

.bg-primary-color--hover:hover,
.bg-primary-color--focus:focus,
.bg-primary-color--focus:hover,
.bg-primary-color--focus-within:focus-within,
.bg-primary-color--active:active,
.bg-primary-color--disabled:disabled {
  background-color: var(--fui-theme-primary-color)}

.bg-primary-background-color {
  background-color: var(--fui-theme-primary-background-color);
}

.bg-primary-background-color--hover:hover,
.bg-primary-background-color--focus:focus,
.bg-primary-background-color--focus:hover,
.bg-primary-background-color--focus-within:focus-within,
.bg-primary-background-color--active:active,
.bg-primary-background-color--disabled:disabled {
  background-color: var(--fui-theme-primary-background-color)}

.accent {
  color: var(--fui-theme-accent-color);
  background-color: var(--fui-theme-accent-background-color);
}

.accent :visited {
  color: var(--fui-theme-accent-color-visited);
}

.accent--hover:hover,
.accent--focus:focus,
.accent--focus:hover,
.accent--focus-within:focus-within,
.accent--active:active,
.accent--disabled:disabled {
  color: var(--fui-theme-accent-color);
  background-color: var(--fui-theme-accent-background-color)}

.accent-inverse {
  color: var(--fui-theme-accent-background-color);
  background-color: var(--fui-theme-accent-color);
}

.accent-inverse :visited {
  color: var(--fui-theme-accent-color-visited);
}

.accent-inverse--hover:hover,
.accent-inverse--focus:focus,
.accent-inverse--focus:hover,
.accent-inverse--focus-within:focus-within,
.accent-inverse--active:active,
.accent-inverse--disabled:disabled {
  color: var(--fui-theme-accent-background-color);
  background-color: var(--fui-theme-accent-color)}

.c-accent-color {
  color: var(--fui-theme-accent-color);
}

.c-accent-color--hover:hover,
.c-accent-color--focus:focus,
.c-accent-color--focus:hover,
.c-accent-color--focus-within:focus-within,
.c-accent-color--active:active,
.c-accent-color--disabled:disabled {
  color: var(--fui-theme-accent-color)}

.c-accent-background-color {
  color: var(--fui-theme-accent-background-color);
}

.c-accent-background-color--hover:hover,
.c-accent-background-color--focus:focus,
.c-accent-background-color--focus:hover,
.c-accent-background-color--focus-within:focus-within,
.c-accent-background-color--active:active,
.c-accent-background-color--disabled:disabled {
  color: var(--fui-theme-accent-background-color)}

.bg-accent-color {
  background-color: var(--fui-theme-accent-color);
}

.bg-accent-color--hover:hover,
.bg-accent-color--focus:focus,
.bg-accent-color--focus:hover,
.bg-accent-color--focus-within:focus-within,
.bg-accent-color--active:active,
.bg-accent-color--disabled:disabled {
  background-color: var(--fui-theme-accent-color)}

.bg-accent-background-color {
  background-color: var(--fui-theme-accent-background-color);
}

.bg-accent-background-color--hover:hover,
.bg-accent-background-color--focus:focus,
.bg-accent-background-color--focus:hover,
.bg-accent-background-color--focus-within:focus-within,
.bg-accent-background-color--active:active,
.bg-accent-background-color--disabled:disabled {
  background-color: var(--fui-theme-accent-background-color)}

.complement {
  color: var(--fui-theme-complement-color);
  background-color: var(--fui-theme-complement-background-color);
}

.complement :visited {
  color: var(--fui-theme-complement-color-visited);
}

.complement--hover:hover,
.complement--focus:focus,
.complement--focus:hover,
.complement--focus-within:focus-within,
.complement--active:active,
.complement--disabled:disabled {
  color: var(--fui-theme-complement-color);
  background-color: var(--fui-theme-complement-background-color)}

.complement-inverse {
  color: var(--fui-theme-complement-background-color);
  background-color: var(--fui-theme-complement-color);
}

.complement-inverse :visited {
  color: var(--fui-theme-complement-color-visited);
}

.complement-inverse--hover:hover,
.complement-inverse--focus:focus,
.complement-inverse--focus:hover,
.complement-inverse--focus-within:focus-within,
.complement-inverse--active:active,
.complement-inverse--disabled:disabled {
  color: var(--fui-theme-complement-background-color);
  background-color: var(--fui-theme-complement-color)}

.c-complement-color {
  color: var(--fui-theme-complement-color);
}

.c-complement-color--hover:hover,
.c-complement-color--focus:focus,
.c-complement-color--focus:hover,
.c-complement-color--focus-within:focus-within,
.c-complement-color--active:active,
.c-complement-color--disabled:disabled {
  color: var(--fui-theme-complement-color)}

.c-complement-background-color {
  color: var(--fui-theme-complement-background-color);
}

.c-complement-background-color--hover:hover,
.c-complement-background-color--focus:focus,
.c-complement-background-color--focus:hover,
.c-complement-background-color--focus-within:focus-within,
.c-complement-background-color--active:active,
.c-complement-background-color--disabled:disabled {
  color: var(--fui-theme-complement-background-color)}

.bg-complement-color {
  background-color: var(--fui-theme-complement-color);
}

.bg-complement-color--hover:hover,
.bg-complement-color--focus:focus,
.bg-complement-color--focus:hover,
.bg-complement-color--focus-within:focus-within,
.bg-complement-color--active:active,
.bg-complement-color--disabled:disabled {
  background-color: var(--fui-theme-complement-color)}

.bg-complement-background-color {
  background-color: var(--fui-theme-complement-background-color);
}

.bg-complement-background-color--hover:hover,
.bg-complement-background-color--focus:focus,
.bg-complement-background-color--focus:hover,
.bg-complement-background-color--focus-within:focus-within,
.bg-complement-background-color--active:active,
.bg-complement-background-color--disabled:disabled {
  background-color: var(--fui-theme-complement-background-color)}

.neutral {
  color: var(--fui-theme-neutral-color);
  background-color: var(--fui-theme-neutral-background-color);
}

.neutral :visited {
  color: var(--fui-theme-neutral-color-visited);
}

.neutral--hover:hover,
.neutral--focus:focus,
.neutral--focus:hover,
.neutral--focus-within:focus-within,
.neutral--active:active,
.neutral--disabled:disabled {
  color: var(--fui-theme-neutral-color);
  background-color: var(--fui-theme-neutral-background-color)}

.neutral-inverse {
  color: var(--fui-theme-neutral-background-color);
  background-color: var(--fui-theme-neutral-color);
}

.neutral-inverse :visited {
  color: var(--fui-theme-neutral-color-visited);
}

.neutral-inverse--hover:hover,
.neutral-inverse--focus:focus,
.neutral-inverse--focus:hover,
.neutral-inverse--focus-within:focus-within,
.neutral-inverse--active:active,
.neutral-inverse--disabled:disabled {
  color: var(--fui-theme-neutral-background-color);
  background-color: var(--fui-theme-neutral-color)}

.c-neutral-color {
  color: var(--fui-theme-neutral-color);
}

.c-neutral-color--hover:hover,
.c-neutral-color--focus:focus,
.c-neutral-color--focus:hover,
.c-neutral-color--focus-within:focus-within,
.c-neutral-color--active:active,
.c-neutral-color--disabled:disabled {
  color: var(--fui-theme-neutral-color)}

.c-neutral-background-color {
  color: var(--fui-theme-neutral-background-color);
}

.c-neutral-background-color--hover:hover,
.c-neutral-background-color--focus:focus,
.c-neutral-background-color--focus:hover,
.c-neutral-background-color--focus-within:focus-within,
.c-neutral-background-color--active:active,
.c-neutral-background-color--disabled:disabled {
  color: var(--fui-theme-neutral-background-color)}

.bg-neutral-color {
  background-color: var(--fui-theme-neutral-color);
}

.bg-neutral-color--hover:hover,
.bg-neutral-color--focus:focus,
.bg-neutral-color--focus:hover,
.bg-neutral-color--focus-within:focus-within,
.bg-neutral-color--active:active,
.bg-neutral-color--disabled:disabled {
  background-color: var(--fui-theme-neutral-color)}

.bg-neutral-background-color {
  background-color: var(--fui-theme-neutral-background-color);
}

.bg-neutral-background-color--hover:hover,
.bg-neutral-background-color--focus:focus,
.bg-neutral-background-color--focus:hover,
.bg-neutral-background-color--focus-within:focus-within,
.bg-neutral-background-color--active:active,
.bg-neutral-background-color--disabled:disabled {
  background-color: var(--fui-theme-neutral-background-color)}

.success {
  color: var(--fui-theme-success-color);
  background-color: var(--fui-theme-success-background-color);
}

.success :visited {
  color: var(--fui-theme-success-color-visited);
}

.success--hover:hover,
.success--focus:focus,
.success--focus:hover,
.success--focus-within:focus-within,
.success--active:active,
.success--disabled:disabled {
  color: var(--fui-theme-success-color);
  background-color: var(--fui-theme-success-background-color)}

.success-inverse {
  color: var(--fui-theme-success-background-color);
  background-color: var(--fui-theme-success-color);
}

.success-inverse :visited {
  color: var(--fui-theme-success-color-visited);
}

.success-inverse--hover:hover,
.success-inverse--focus:focus,
.success-inverse--focus:hover,
.success-inverse--focus-within:focus-within,
.success-inverse--active:active,
.success-inverse--disabled:disabled {
  color: var(--fui-theme-success-background-color);
  background-color: var(--fui-theme-success-color)}

.c-success-color {
  color: var(--fui-theme-success-color);
}

.c-success-color--hover:hover,
.c-success-color--focus:focus,
.c-success-color--focus:hover,
.c-success-color--focus-within:focus-within,
.c-success-color--active:active,
.c-success-color--disabled:disabled {
  color: var(--fui-theme-success-color)}

.c-success-background-color {
  color: var(--fui-theme-success-background-color);
}

.c-success-background-color--hover:hover,
.c-success-background-color--focus:focus,
.c-success-background-color--focus:hover,
.c-success-background-color--focus-within:focus-within,
.c-success-background-color--active:active,
.c-success-background-color--disabled:disabled {
  color: var(--fui-theme-success-background-color)}

.bg-success-color {
  background-color: var(--fui-theme-success-color);
}

.bg-success-color--hover:hover,
.bg-success-color--focus:focus,
.bg-success-color--focus:hover,
.bg-success-color--focus-within:focus-within,
.bg-success-color--active:active,
.bg-success-color--disabled:disabled {
  background-color: var(--fui-theme-success-color)}

.bg-success-background-color {
  background-color: var(--fui-theme-success-background-color);
}

.bg-success-background-color--hover:hover,
.bg-success-background-color--focus:focus,
.bg-success-background-color--focus:hover,
.bg-success-background-color--focus-within:focus-within,
.bg-success-background-color--active:active,
.bg-success-background-color--disabled:disabled {
  background-color: var(--fui-theme-success-background-color)}

.info {
  color: var(--fui-theme-info-color);
  background-color: var(--fui-theme-info-background-color);
}

.info :visited {
  color: var(--fui-theme-info-color-visited);
}

.info--hover:hover,
.info--focus:focus,
.info--focus:hover,
.info--focus-within:focus-within,
.info--active:active,
.info--disabled:disabled {
  color: var(--fui-theme-info-color);
  background-color: var(--fui-theme-info-background-color)}

.info-inverse {
  color: var(--fui-theme-info-background-color);
  background-color: var(--fui-theme-info-color);
}

.info-inverse :visited {
  color: var(--fui-theme-info-color-visited);
}

.info-inverse--hover:hover,
.info-inverse--focus:focus,
.info-inverse--focus:hover,
.info-inverse--focus-within:focus-within,
.info-inverse--active:active,
.info-inverse--disabled:disabled {
  color: var(--fui-theme-info-background-color);
  background-color: var(--fui-theme-info-color)}

.c-info-color {
  color: var(--fui-theme-info-color);
}

.c-info-color--hover:hover,
.c-info-color--focus:focus,
.c-info-color--focus:hover,
.c-info-color--focus-within:focus-within,
.c-info-color--active:active,
.c-info-color--disabled:disabled {
  color: var(--fui-theme-info-color)}

.c-info-background-color {
  color: var(--fui-theme-info-background-color);
}

.c-info-background-color--hover:hover,
.c-info-background-color--focus:focus,
.c-info-background-color--focus:hover,
.c-info-background-color--focus-within:focus-within,
.c-info-background-color--active:active,
.c-info-background-color--disabled:disabled {
  color: var(--fui-theme-info-background-color)}

.bg-info-color {
  background-color: var(--fui-theme-info-color);
}

.bg-info-color--hover:hover,
.bg-info-color--focus:focus,
.bg-info-color--focus:hover,
.bg-info-color--focus-within:focus-within,
.bg-info-color--active:active,
.bg-info-color--disabled:disabled {
  background-color: var(--fui-theme-info-color)}

.bg-info-background-color {
  background-color: var(--fui-theme-info-background-color);
}

.bg-info-background-color--hover:hover,
.bg-info-background-color--focus:focus,
.bg-info-background-color--focus:hover,
.bg-info-background-color--focus-within:focus-within,
.bg-info-background-color--active:active,
.bg-info-background-color--disabled:disabled {
  background-color: var(--fui-theme-info-background-color)}

.warn {
  color: var(--fui-theme-warn-color);
  background-color: var(--fui-theme-warn-background-color);
}

.warn :visited {
  color: var(--fui-theme-warn-color-visited);
}

.warn--hover:hover,
.warn--focus:focus,
.warn--focus:hover,
.warn--focus-within:focus-within,
.warn--active:active,
.warn--disabled:disabled {
  color: var(--fui-theme-warn-color);
  background-color: var(--fui-theme-warn-background-color)}

.warn-inverse {
  color: var(--fui-theme-warn-background-color);
  background-color: var(--fui-theme-warn-color);
}

.warn-inverse :visited {
  color: var(--fui-theme-warn-color-visited);
}

.warn-inverse--hover:hover,
.warn-inverse--focus:focus,
.warn-inverse--focus:hover,
.warn-inverse--focus-within:focus-within,
.warn-inverse--active:active,
.warn-inverse--disabled:disabled {
  color: var(--fui-theme-warn-background-color);
  background-color: var(--fui-theme-warn-color)}

.c-warn-color {
  color: var(--fui-theme-warn-color);
}

.c-warn-color--hover:hover,
.c-warn-color--focus:focus,
.c-warn-color--focus:hover,
.c-warn-color--focus-within:focus-within,
.c-warn-color--active:active,
.c-warn-color--disabled:disabled {
  color: var(--fui-theme-warn-color)}

.c-warn-background-color {
  color: var(--fui-theme-warn-background-color);
}

.c-warn-background-color--hover:hover,
.c-warn-background-color--focus:focus,
.c-warn-background-color--focus:hover,
.c-warn-background-color--focus-within:focus-within,
.c-warn-background-color--active:active,
.c-warn-background-color--disabled:disabled {
  color: var(--fui-theme-warn-background-color)}

.bg-warn-color {
  background-color: var(--fui-theme-warn-color);
}

.bg-warn-color--hover:hover,
.bg-warn-color--focus:focus,
.bg-warn-color--focus:hover,
.bg-warn-color--focus-within:focus-within,
.bg-warn-color--active:active,
.bg-warn-color--disabled:disabled {
  background-color: var(--fui-theme-warn-color)}

.bg-warn-background-color {
  background-color: var(--fui-theme-warn-background-color);
}

.bg-warn-background-color--hover:hover,
.bg-warn-background-color--focus:focus,
.bg-warn-background-color--focus:hover,
.bg-warn-background-color--focus-within:focus-within,
.bg-warn-background-color--active:active,
.bg-warn-background-color--disabled:disabled {
  background-color: var(--fui-theme-warn-background-color)}

.danger {
  color: var(--fui-theme-danger-color);
  background-color: var(--fui-theme-danger-background-color);
}

.danger :visited {
  color: var(--fui-theme-danger-color-visited);
}

.danger--hover:hover,
.danger--focus:focus,
.danger--focus:hover,
.danger--focus-within:focus-within,
.danger--active:active,
.danger--disabled:disabled {
  color: var(--fui-theme-danger-color);
  background-color: var(--fui-theme-danger-background-color)}

.danger-inverse {
  color: var(--fui-theme-danger-background-color);
  background-color: var(--fui-theme-danger-color);
}

.danger-inverse :visited {
  color: var(--fui-theme-danger-color-visited);
}

.danger-inverse--hover:hover,
.danger-inverse--focus:focus,
.danger-inverse--focus:hover,
.danger-inverse--focus-within:focus-within,
.danger-inverse--active:active,
.danger-inverse--disabled:disabled {
  color: var(--fui-theme-danger-background-color);
  background-color: var(--fui-theme-danger-color)}

.c-danger-color {
  color: var(--fui-theme-danger-color);
}

.c-danger-color--hover:hover,
.c-danger-color--focus:focus,
.c-danger-color--focus:hover,
.c-danger-color--focus-within:focus-within,
.c-danger-color--active:active,
.c-danger-color--disabled:disabled {
  color: var(--fui-theme-danger-color)}

.c-danger-background-color {
  color: var(--fui-theme-danger-background-color);
}

.c-danger-background-color--hover:hover,
.c-danger-background-color--focus:focus,
.c-danger-background-color--focus:hover,
.c-danger-background-color--focus-within:focus-within,
.c-danger-background-color--active:active,
.c-danger-background-color--disabled:disabled {
  color: var(--fui-theme-danger-background-color)}

.bg-danger-color {
  background-color: var(--fui-theme-danger-color);
}

.bg-danger-color--hover:hover,
.bg-danger-color--focus:focus,
.bg-danger-color--focus:hover,
.bg-danger-color--focus-within:focus-within,
.bg-danger-color--active:active,
.bg-danger-color--disabled:disabled {
  background-color: var(--fui-theme-danger-color)}

.bg-danger-background-color {
  background-color: var(--fui-theme-danger-background-color);
}

.bg-danger-background-color--hover:hover,
.bg-danger-background-color--focus:focus,
.bg-danger-background-color--focus:hover,
.bg-danger-background-color--focus-within:focus-within,
.bg-danger-background-color--active:active,
.bg-danger-background-color--disabled:disabled {
  background-color: var(--fui-theme-danger-background-color)}

body, p {
  font-family: var(--fui-body-font-family);
  font-size: var(--fui-body-font-size);
  line-height: var(--fui-body-line-height);
  font-weight: var(--fui-body-font-weight);
  font-style: var(--fui-body-font-style);
  font-variant: var(--fui-body-font-variant);
  font-kerning: var(--fui-body-font-kerning);
}

h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6 {
  font-family: var(--fui-heading-font-family);
  line-height: var(--fui-heading-line-height);
}

h1, .h1 {
  font-size: var(--fui-h1-font-size);
  font-weight: 100;
}

h2, .h2 {
  font-size: var(--fui-h2-font-size);
}

h3, .h3 {
  font-size: var(--fui-h3-font-size);
}

h4, .h4 {
  font-size: var(--fui-h4-font-size);
}

h5, .h5 {
  font-size: var(--fui-h5-font-size);
}

h6, .h6 {
  font-size: var(--fui-h6-font-size);
}

.bold {
  font-weight: bold;
}

.italic {
  font-style: italic;
}

.fs-smaller {
  font-size: calc(1em / var(--fui-font-size-scale));
}

.fs-medium {
  font-size: 1rem;
}

.fs-larger {
  font-size: calc(1em * var(--fui-font-size-scale));
}

.body {
  overflow-x: hidden;
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: auto 1fr auto;
  grid-template-areas: "header" "main" "footer";
  min-height: 100vh;
}

.viewport {
  width: 100vw;
  height: 100vh;
}

.h-viewport {
  height: 100vh;
}

.h-100 {
  height: 100%;
}

.minh-viewport {
  min-height: 100vh;
}

.minh-100 {
  min-height: 100%;
}

.maxh-viewport {
  max-height: 100vh;
}

.maxh-100 {
  max-height: 100%;
}

.w-viewport {
  width: 100vw;
}

.w-100 {
  width: 100%;
}

.w-fit-content {
  width: fit-content;
}

.w-page {
  width: var(--fui-page-width);
}

.page {
  padding: var(--fui-spacing-page);
  display: flex;
  flex-direction: column;
  gap: var(--fui-spacing-text);
}

.page-x {
  padding: 0 var(--fui-spacing-page-x);
}

.page-y {
  padding: var(--fui-spacing-page-y) 0;
}

.row {
  display: flex;
  flex-direction: row;
}

.column {
  display: flex;
  flex-direction: column;
}

/* use flex instead of grid as grid screws up responsive images */

.start-start, .start {
  display: flex;
  justify-content: start;
  align-items: start;
}

.start-center {
  display: flex;
  justify-content: start;
  align-items: center;
}

.start-end {
  display: flex;
  justify-content: start;
  align-items: end;
}

.center-start {
  display: flex;
  justify-content: center;
  align-items: start;
}

.center-center, .center {
  display: flex;
  justify-content: center;
  align-items: center;
}

.center-end {
  display: flex;
  justify-content: center;
  align-items: end;
}

.end-start {
  display: flex;
  justify-content: end;
  align-items: start;
}

.end-center {
  display: flex;
  justify-content: end;
  align-items: center;
}

.end-end, .end {
  display: flex;
  justify-content: end;
  align-items: end;
}

.space-between {
  place-content: space-between;
  justify-content: space-between;
}

.space-around {
  place-content: space-around;
  justify-content: space-around;
}

.wrap {
  flex-wrap: wrap;
}

.ta-start {
  text-align: start;
}

.ta-center {
  text-align: center;
}

.ta-end {
  text-align: end;
}

.p {
  padding: var(--fui-spacing-y-min) var(--fui-spacing-x-min);
}

.pt {
  padding-top: var(--fui-spacing-y-min);
}

.pr {
  padding-right: var(--fui-spacing-x-min);
}

.pb {
  padding-bottom: var(--fui-spacing-y-min);
}

.pl {
  padding-left: var(--fui-spacing-x-min);
}

.px {
  padding-left: var(--fui-spacing-x-min);
  padding-right: var(--fui-spacing-x-min);
}

.py {
  padding-top: var(--fui-spacing-y-min);
  padding-bottom: var(--fui-spacing-y-min);
}

.p-0 {
  padding: 0;
}

.pt-0 {
  padding-top: 0;
}

.pr-0 {
  padding-right: 0;
}

.pb-0 {
  padding-bottom: 0;
}

.pl-0 {
  padding-left: 0;
}

.p-responsive {
  padding: var(--fui-spacing-responsive-y) var(--fui-spacing-responsive-x);
}

.pt-responsive {
  padding-top: var(--fui-spacing-responsive-y);
}

.pr-responsive {
  padding-right: var(--fui-spacing-responsive-x);
}

.pb-responsive {
  padding-bottom: var(--fui-spacing-responsive-y);
}

.pl-responsive {
  padding-left: var(--fui-spacing-responsive-x);
}

.px-responsive {
  padding-left: var(--fui-spacing-responsive-x);
  padding-right: var(--fui-spacing-responsive-x);
}

.py-responsive {
  padding-top: var(--fui-spacing-responsive-y);
  padding-bottom: var(--fui-spacing-responsive-y);
}

.m {
  margin: var(--fui-spacing-y-min) var(--fui-spacing-x-min);
}

.mt {
  margin-top: var(--fui-spacing-y-min);
}

.mr {
  margin-right: var(--fui-spacing-x-min);
}

.mb {
  margin-bottom: var(--fui-spacing-y-min);
}

.ml {
  margin-left: var(--fui-spacing-x-min);
}

.mx {
  margin-left: var(--fui-spacing-x-min);
  margin-right: var(--fui-spacing-x-min);
}

.my {
  margin-top: var(--fui-spacing-y-min);
  margin-bottom: var(--fui-spacing-y-min);
}

.m-0 {
  margin: 0;
}

.mt-0 {
  margin-top: 0;
}

.mr-0 {
  margin-right: 0;
}

.mb-0 {
  margin-bottom: 0;
}

.ml-0 {
  margin-left: 0;
}

.m-responsive {
  margin: var(--fui-spacing-responsive-y) var(--fui-spacing-responsive-x);
}

.mt-responsive {
  margin-top: var(--fui-spacing-responsive-y);
}

.mr-responsive {
  margin-right: var(--fui-spacing-responsive-x);
}

.mb-responsive {
  margin-bottom: var(--fui-spacing-responsive-y);
}

.ml-responsive {
  margin-left: var(--fui-spacing-responsive-x);
}

.mx-responsive {
  margin-left: var(--fui-spacing-responsive-x);
  margin-right: var(--fui-spacing-responsive-x);
}

.my-responsive {
  margin-top: var(--fui-spacing-responsive-y);
  margin-bottom: var(--fui-spacing-responsive-y);
}

.ml-auto {
  margin-left: auto;
}

.mr-auto {
  margin-right: auto;
}

.gap-base {
  gap: var(--fui-spacing-base);
}

.gap-text {
  gap: var(--fui-spacing-text);
}

.block {
  display: block;
}

.inline {
  display: inline;
}

.inline-block {
  display: inline-block;
}

.flex, [class^="fd-"], [class*=" fd-"] {
  display: flex;
  flex-direction: column;
}

.grid {
  display: grid;
}

.contents {
  display: contents;
}

.static {
  position: static;
}

.relative {
  position: relative;
}

.absolute {
  position: absolute;
}

.sticky {
  position: sticky;
}

.fixed {
  position: fixed;
}

.t-default {
  transition: var(--fui-animation-default-speed) var(--fui-animation-default-timing-function);
}

.border-transparent {
  border-color: transparent;
}

.border {
  border: var(--fui-border-width) solid var(--fui-color-border);
  border-radius: var(--fui-border-radius);
}

.b {
  border: var(--fui-border-width) solid var(--fui-color-border);
}

.bt {
  border-top: var(--fui-border-width) solid var(--fui-color-border);
}

.br {
  border-right: var(--fui-border-width) solid var(--fui-color-border);
}

.bb {
  border-bottom: var(--fui-border-width) solid var(--fui-color-border);
}

.bl {
  border-left: var(--fui-border-width) solid var(--fui-color-border);
}

:root {
  --fui-box-shadow-1: 0 1px 2px 0 rgba(0, 0, 0, 0.2);
  --fui-box-shadow-2: 0 1px 4px 0 rgba(0, 0, 0, 0.2);
  --fui-box-shadow-3: 0 2px 8px 0 rgba(0, 0, 0, 0.2);
  --fui-box-shadow-4: 0 4px 16px 0 rgba(0, 0, 0, 0.2);
  --fui-box-shadow-5: 0 8px 32px 0 rgba(0, 0, 0, 0.2);
  --fui-box-shadow-6: 0 16px 64px 0 rgba(0, 0, 0, 0.2);
}

.bs-0 {
  box-shadow: none;
}

.bs-1 {
  box-shadow: var(--fui-box-shadow-1);
}

.bs-1--hover:hover,
.bs-1--focus:focus,
.bs-1--focus:hover,
.bs-1--focus-within:focus-within,
.bs-1--active:active,
.bs-1--disabled:disabled {
  box-shadow: var(--fui-box-shadow-1)}

.bs-2 {
  box-shadow: var(--fui-box-shadow-2);
}

.bs-2--hover:hover,
.bs-2--focus:focus,
.bs-2--focus:hover,
.bs-2--focus-within:focus-within,
.bs-2--active:active,
.bs-2--disabled:disabled {
  box-shadow: var(--fui-box-shadow-2)}

.bs-3 {
  box-shadow: var(--fui-box-shadow-3);
}

.bs-3--hover:hover,
.bs-3--focus:focus,
.bs-3--focus:hover,
.bs-3--focus-within:focus-within,
.bs-3--active:active,
.bs-3--disabled:disabled {
  box-shadow: var(--fui-box-shadow-3)}

.bs-4 {
  box-shadow: var(--fui-box-shadow-4);
}

.bs-4--hover:hover,
.bs-4--focus:focus,
.bs-4--focus:hover,
.bs-4--focus-within:focus-within,
.bs-4--active:active,
.bs-4--disabled:disabled {
  box-shadow: var(--fui-box-shadow-4)}

.bs-5 {
  box-shadow: var(--fui-box-shadow-5);
}

.bs-5--hover:hover,
.bs-5--focus:focus,
.bs-5--focus:hover,
.bs-5--focus-within:focus-within,
.bs-5--active:active,
.bs-5--disabled:disabled {
  box-shadow: var(--fui-box-shadow-5)}

.bs-6 {
  box-shadow: var(--fui-box-shadow-6);
}

.bs-6--hover:hover,
.bs-6--focus:focus,
.bs-6--focus:hover,
.bs-6--focus-within:focus-within,
.bs-6--active:active,
.bs-6--disabled:disabled {
  box-shadow: var(--fui-box-shadow-6)}
`;