import { readFile, writeFile, stat, mkdir, readdir } from 'node:fs/promises';
import { isAbsolute, join, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import { transform } from 'lightningcss';
import utilityStyles from '../src/css/utilities/index.css.js';

const srcDir = join(import.meta.dirname, '..', 'src');
const cssDir = join(srcDir, 'css');
const componentsDir = join(srcDir, 'components');

const args = parseArgs({
  options: {
    destination: {
      type: 'string',
      alias: 'd',
      default: process.cwd()
    },
    exclude: {
      type: 'string',
      alias: 'e',
    },
    include: {
      type: 'string',
      alias: 'i',
    },
    merge: {
      type: 'string',
      alias: 'm',
      default: join(cssDir, 'variables.css')
    },
    source: {
      type: 'string',
      alias: 's'
    },
    transform: {
      type: 'string',
      default: 'sourceMap,minify'
    },
    utilities: {
      type: 'string',
      alias: 'u',
    }
  }
});

const { source, destination, exclude, include, merge, utilities } = args.values;
const t = args.transform?.split(',') ?? [];
const [ sourceMap, minify ] = [t.includes('map'), t.includes('minify')];
const destinationDir = isAbsolute(destination) ? destination : join(process.cwd(), destination);

if (stat(destinationDir).catch(() => false)) {
  await mkdir(args.values.destination, { recursive: true });
}

// get variables
let variableCss = '';
let defaultVariables = '';
if (source == null || join.trim() !== '') {
  // TODO: 
  defaultVariables = await readFile(merge, 'utf-8');
}
if (source != null) {
  sourceFile = isAbsolute(source) ? source : join(process.cwd(), source);
  variableCss = await readFile(sourceFile, 'utf-8');
  if (merge) {
    // TODO: Merge variables
    variableCss = `${defaultVariables}\n${variableCss}`;
  }
}
else {
  variableCss = defaultVariables;
}

// include/exclude utility css files
const utilityKeys = utilities != null ? utilities.split(',') : Object.keys(utilityStyles);
const utilityCss = Object.entries(utilityStyles).filter(([key, _]) => utilityKeys.includes(key)).map(([key, style]) => style.cssText).join('\n');

// include/exclude component css files
let componentFiles = (await readdir(componentsDir, {recursive: true})).filter(file => file.endsWith('.css.js'));
if (include != null) {
  const includeFiles = include.split(',').map(file => file.trim());
  componentFiles = componentFiles.filter(file => includeFiles.includes(file));
}
else if (exclude != null) {
  const excludeFiles = exclude.split(',').map(file => file.trim());
  componentFiles = componentFiles.filter(file => !excludeFiles.includes(file));
}

const componentCss = (await Promise.all(
  componentFiles.map(async file => {
    try {
      return (await import(join(componentsDir, file))).default.cssText;
    } catch (error) {
      console.error(`Error reading ${file}: ${error.message}`);
    }
  })
)).join('\n');

const css = ['/** AUTOGENERATED **/', variableCss, utilityCss, componentCss].join('\n');

await writeFile(join(destinationDir, 'fui.css'), css);

if (minify) {
  const { code, map } = transform({
    filename: 'fui.css',
    code: Buffer.from(css, 'utf-8'),
    minify: true,
    sourceMap
  });
  await writeFile(join(destinationDir, 'fui.min.css'), code);
  await writeFile(join(destinationDir, 'fui.min.css.map'), map);
}
else {
  await writeFile(join(process.cwd(), 'fui.css'), css);
}
